feat: new configuration system, config subcommand
hetznercloud/cli pull request #736
Opened 2024-04-19 11:11 UTC by phm07

This PR implements the new configuration system as described in #762.

Closes #762
In preparation for #434

2024-05-03 16:01 UTC, apricote commented on internal/cmd/firewall/describe.go
> +					cmd.Print("    Origin IPs:\n")
Is this change related to the PR or did it accidentally slip in?

2024-05-08 13:19 UTC, jooola reviewed
Overall, I like how it is structured.

I think a few refactoring passes are needed before this can be merged.

I also noticed that the viper library already ships our previous toml library, so might be shipping both. Are we ok with the binary size?

2024-05-08 13:19 UTC, jooola commented on internal/state/config/config.go
> -		return err
Happy not to see this 0777 in the new code, but shouldn't we keep the config dir creation behavior?

2024-05-08 13:19 UTC, jooola commented on internal/state/config/options.go
> +type OptionFlag int
Should we rename this to `OptionFeature`? I have and will be confused by this naming more than once.

e.g. `!o.HasFlag(OptionFlagEnv)` => `!o.HasFeature(OptionFeatureEnv)`

2024-05-23 14:19 UTC, apricote reviewed
Partial review (its a huge PR ;) ), will continue tomorrow :)

2024-05-28 06:52 UTC, apricote requested changes

2024-05-28 06:52 UTC, apricote commented on internal/state/config/preferences.go
> +	configKey := strings.ReplaceAll(strings.ToLower(key), "-", "_")
The `Get`, `Set` and `Unset` methods share a lot of common code related to the config code and path splitting. Is there some way to make them share the behaviour?

2024-05-28 06:52 UTC, apricote commented on internal/state/config/preferences.go
> +			break
Should this be reported as a warning/corrupt config file?

2024-05-28 06:52 UTC, apricote commented on internal/state/config/preferences_test.go
> +func TestPreferences_Validate(t *testing.T) {
Can you add a test for nested options?

2024-05-28 06:52 UTC, apricote commented on internal/state/config/preferences_test.go
> +func TestPreferences_Get(t *testing.T) {
Can you add a test for a missing nested option?

2024-05-28 06:52 UTC, apricote commented on internal/cmd/config/add.go
> +			}),
Is there any way to only suggest list options?

2024-05-28 06:52 UTC, apricote commented on internal/cmd/config/add.go
> +	if util.IsNil(ctx) {
You could also branch on `global` here.

2024-05-28 06:52 UTC, apricote commented on internal/cmd/config/get.go
> +
```suggestion
	key := args[0]
	
	opt := config.Options[key]
	if opt == nil {
		return fmt.Errorf("unknown key: %s", key)
	}

```

2024-05-28 06:52 UTC, apricote commented on internal/cmd/config/get.go
> +		}
This code is duplicated between `get.go` and `list.go`. I think this makes more sense to have in `state/config/config.go`. That way `config.Reset()` could also be dropped from the interface.

2024-05-28 06:52 UTC, apricote commented on internal/cmd/config/set.go
> +		Long:                  "Set a configuration value. For a list of all available configuration options, run 'hcloud help config'.",
I think we should document the accepted values for durations. This is not obvious for non-go devs.

2024-05-29 13:11 UTC, apricote commented on internal/cmd/config/set.go
> +		Long:                  "Set a configuration value. For a list of all available configuration options, run 'hcloud help config'.",
Adding a quick description in either `hcloud config --help` or `hcloud config set --help` sounds good. While this is very intuitive, you need to know that it exists in the first place. People could expect that this is seconds, milliseconds, ...

2024-05-31 12:42 UTC, jooola reviewed
Took another look.

Do you think it would be possible to add the `config.OptionQuiet` options inside the config struct? This way we would only have the config struct in the state and get the value from it?

So instead of `config.OptionQuiet.Get(s.Config())` we would simply have `s.Config().Quiet()` ?


Other than that, there is a bunch of code that can be deduplicated, extracted in smaller functions, so the higher level logic is easier to understand.

2024-05-31 12:42 UTC, jooola commented on internal/state/config/config.go
> +		f, err := os.OpenFile(cfg.path, os.O_WRONLY|os.O_CREATE|os.O_APPEND|os.O_TRUNC, 0600)
I am not sure if the append flag is needed here.

2024-05-31 12:44 UTC, jooola commented on internal/state/config/options.go
> +type OptionFlag int
Alright, maybe with some getting used to I'll get the hand of it.

2024-05-31 12:50 UTC, jooola commented on internal/cmd/config/config.go
> +`,
What I had in mind was to maybe embed an entire markdown file, that will be easier to maintain in the long run, and render it in the terminal (e.g. https://github.com/charmbracelet/glamour).

Maybe using some template function, we can embed the preferences as Markdown table as well.

2024-06-05 10:27 UTC, jooola commented
> There would be a lot of code duplication. There would need to be a method implemented on the config struct for every single option. Also there would need to be a map that stores all option. There is no way to create such a map automatically when getter methods are used to access options. Right now newOpt is used to handle that.

I don't think it increases the duplication too much, it is moving some code around. Instead of having "complex" code in the business logic, we have dumb code in the config package.

> Testing would be a lot harder since options would be hard coded. Currently, the option set is extended for some tests. This is for example used to test nested options which don't exist yet.

I am not sure if this is a real problem, we could have dedicated config struct for testing that embed the normal config struct. 

> It would unnecessarily clutter the Config interface.

I prefer to clutter the config interface instead of the business code. Ensuring a proper separation of concern with simple APIs, will make the project easier to work with.

> Feel free to comment those parts in your review.

Will do.

2024-06-05 10:30 UTC, jooola commented
> There would be a lot of code duplication. There would need to be a method implemented on the config struct for every single option. Also there would need to be a map that stores all option. There is no way to create such a map automatically when getter methods are used to access options. Right now newOpt is used to handle that.

That said, I don't have a strong opinion. I just wanted to discuss the topic, to see if we can have an even better API.

2024-06-05 10:47 UTC, jooola reviewed
This is getting better and better, I like it!

I added the few comment in places I though we could deduplicate/move some code.

2024-06-05 10:47 UTC, jooola commented on internal/cmd/config/add.go
> +	}
I saw this appear multiple times in the code, might be a candidate for a dedicated function.

2024-06-05 10:47 UTC, jooola commented on internal/cmd/config/get.go
> +}
We do not provide config key completion here?

2024-06-05 10:47 UTC, jooola commented on internal/cmd/config/add.go
> +	}
I saw this appear multiple times in the code, might be a candidate for a dedicated function.

2024-06-05 10:47 UTC, jooola commented on internal/cmd/config/remove.go
> +			}),
I saw this appear multiple times in the code, might be a candidate for a dedicated function.

2024-06-05 10:47 UTC, jooola commented on internal/cmd/config/remove.go
> +	}
I saw this appear multiple times in the code, might be a candidate for a dedicated function.

2024-06-05 10:47 UTC, jooola commented on internal/cmd/config/set.go
> +			return fmt.Errorf("invalid boolean value: %s", value)
strconv.ParseBool ?

2024-06-05 10:47 UTC, jooola commented on internal/cmd/config/list.go
> +		}
Should the 'redacted' logic be moved to the option methods ? And have a dedicated method when allowSensistive is set?

2024-06-05 10:47 UTC, jooola commented on internal/cmd/config/set.go
> +		}
Does it make sense to move the Parsing/Formatting logic in the Option?

2024-06-05 11:43 UTC, jooola commented on internal/cmd/config/set.go
> +			return fmt.Errorf("invalid boolean value: %s", value)
Then I believe this could also be a candidate for a dedicated function :)

2024-06-05 12:44 UTC, jooola commented on internal/cmd/config/set.go
> +			return fmt.Errorf("invalid boolean value: %s", value)
To improve readability and split concerns: if I read code about the set command, I don't to see 6 lines only dedicated to parsing a bool value. Having a single function can make the code way more readable.

2024-06-05 13:09 UTC, jooola commented
> `config.OptionQuiet.Get(s.Config())` => `s.Config().Quiet()`

Alright, case close from my side then.

2024-06-05 14:53 UTC, jooola commented on README.md
> +The hcloud CLI tool allows configuration using following methods:
Yes work for me.

2024-06-06 13:10 UTC, apricote approved these changes
Awesome! Looking really good now :)

(We will _for sure_ find some bugs and rough edges after merging, but that happens always).

2024-06-06 14:52 UTC, merged