feat: allow configuring default sort columns for each supported resource
hetznercloud/cli pull request #795
Opened 2024-06-26 13:47 UTC by phm07

This PR adds options to configure the default sorting column for each resource that supports the `list` command.
See #418 and #434

2024-06-26 13:53 UTC, jooola commented
Do you think it's possible to decouple the `SortOption` and the per resource sort arguments? Similar to the tables columns?

2024-06-26 15:00 UTC, jooola commented
> Is this too much? Or should we keep all the entries fort sort.[resource]?

I'd rather keep it explicit, unless we have a clear list of resource names.

> sort.loadbalancertype │ HCLOUD_SORT.LOADBALANCERTYPE

Could we keep the `_` or `-` in the names? The env variable name is not the final ones right?

2024-06-27 09:58 UTC, jooola commented
Nope, env vars cannot have dots: 

Environment variable names used by the utilities in the Shell and Utilities volume of POSIX.1-2017 consist solely of uppercase letters, digits, and the <underscore> ( '_' ) from the characters defined in [Portable Character Set](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap06.html#tagtcjh_3) and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names. Uppercase and lowercase letters shall retain their unique identities and shall not be folded together. The name space of environment variable names containing lowercase letters is reserved for applications. Applications can define any environment variables with names from this name space without modifying the behavior of the standard utilities.


https://pubs.opengroup.org/onlinepubs/9699919799/

2024-06-27 14:33 UTC, apricote commented
Without taking a look at the code:

- I think the options should be the same as the subcommands: `hcloud load-balancer` -> `sort.load-balancer`
- In the docs I would prefer to have a single element `sort.<resource>` to keep this reasonably small.
- I would add a section in `hcloud config --help` that describes these options in general

2024-07-03 13:33 UTC, apricote approved these changes
:rocket:

2024-07-04 12:20 UTC, apricote commented
While testing this, I found that `hcloud config add` adds to the front of the list. I found this counterintuitive. I wanted to set a default for `hcloud image list --sort name:asc --sort created:asc` so I ran:

```
$ hcloud config add sort.image name:asc
$ hcloud config add sort.image created:asc
```

Thinking it would end us as `[name:asc created:asc`]. Turned out it was the other way around, and running `hcloud image list` now orders the other way around.

```
$ hcloud config get sort.image
[created:asc name:asc]
```


---

So feature works technically, but the UX was unexpected

2024-07-04 12:22 UTC, apricote commented
Even with `hcloud config set sort.image name:asc created:asc` its being saved in the wrong order.

2024-07-05 07:40 UTC, apricote requested changes
I noticed that this PR does not compile anymore because of #798. Could you rebase this PR and fix the compilation error?

The functionality works great now!

2024-07-05 07:40 UTC, apricote commented on internal/state/config/options.go
> +	)
I noticed that the API does not support sorting for:

- ISOs
- Load Balancer Types
- Networks
- Server Types

I think we should remove these options and only add them if the API also supports this.

2024-07-10 14:32 UTC, apricote approved these changes
:rocket:

2024-07-10 15:52 UTC, merged

2026-11-18 08:56 UTC, jooola commented
@phm07 Do you remember why always registered the sort option, and why we added a warning when the --sort option was used but not supported? Did you prefer not to fail if sorting was not supported?

Right the docs is also invalid and we are considering removing that flag from the commands that do not support this #1536 and in a similar style #1547